name: WhatsApp Weather Bot

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 10AM Singapore Time (2AM UTC)
  workflow_dispatch:

jobs:
  send-weather:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
        TWILIO_FROM_NUMBER: ${{ secrets.TWILIO_FROM_NUMBER }}
        RECIPIENTS: ${{ secrets.RECIPIENTS }}
      run: python weatherbot.py
